src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CompanyName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ContactName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ContactEmail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ContactPhone;

    /**
     * @ORM\OneToMany(targetEntity=Website::class, mappedBy="Client")
     */
    private $Websites;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __construct()
    {
        $this->Websites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompanyName(): ?string
    {
        return $this->CompanyName;
    }

    public function setCompanyName(string $CompanyName): self
    {
        $this->CompanyName = $CompanyName;

        return $this;
    }

    public function getContactName(): ?string
    {
        return $this->ContactName;
    }

    public function setContactName(string $ContactName): self
    {
        $this->ContactName = $ContactName;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->ContactEmail;
    }

    public function setContactEmail(?string $ContactEmail): self
    {
        $this->ContactEmail = $ContactEmail;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->ContactPhone;
    }

    public function setContactPhone(?string $ContactPhone): self
    {
        $this->ContactPhone = $ContactPhone;

        return $this;
    }

    /**
     * @return Collection|Website[]
     */
    public function getWebsites(): Collection
    {
        return $this->Websites;
    }

    public function addWebsite(Website $website): self
    {
        if (!$this->Websites->contains($website)) {
            $this->Websites[] = $website;
            $website->setClient($this);
        }

        return $this;
    }

    public function removeWebsite(Website $website): self
    {
        if ($this->Websites->removeElement($website)) {
            // set the owning side to null (unless already changed)
            if ($website->getClient() === $this) {
                $website->setClient(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Entity/Website.php
<?php

namespace App\Entity;

use App\Repository\WebsiteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WebsiteRepository::class)
 */
class Website
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Link;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="Websites")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PHP;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getPHP(): ?string
    {
        return $this->PHP;
    }

    public function setPHP(?string $PHP): self
    {
        $this->PHP = $PHP;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/WebsiteType.php
<?php

namespace App\Form;

use App\Entity\Website;
use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\Url;
use Symfony\Component\Validator\Constraints\Regex;

class WebsiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name', TextType::class, [
                'constraints' => [
                    new Regex("/^.{2,50}+$/")
                ],
                'required' => true,
                'label' => 'Nom du site',
            ])
            ->add('Link', TextType::class, [
                'constraints' => [
                    new Url()
                ],
                'required' => true,
                'label' => 'Lien vers le site',
            ])
            ->add('Client', EntityType::class, [
                'class' => Client::class,
                'choice_label' => 'companyName',
                'required' => true,
                'label' => 'Client',
            ])
            ->add('PHP', ChoiceType::class, [
                'required' => false,
                'choices'  => [
                    '7.4' => "7.4",
                    '7.3' => "7.3",
                    '7.2' => "7.2",
                    '7.1' => "7.1",
                    '7.0' => "7.0",
                ],
                'label' => 'Version PHP',
                'empty_data' => null,
                'placeholder' => 'Aucune',
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Ajouter',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Website::class,
        ]);
    }
}

src/Controller/WebsiteController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Website;
use DateTime;
use App\Form\WebsiteType;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Validator\Constraints\Url as UrlConstraint;

class WebsiteController extends AbstractController
{
    /**
     * @Route("/", name="website")
     */
    public function websites(Request $request): Response
    {
        $filtered = false;
        $message = null;
        $error = null;
        $easterEgg = false;

        if ($request->query->get('search'))
        {
            $search = $request->query->get('search');

            if (is_string($search))
            {
                $filtered = true;
                $search = trim($search);

                if (strtolower($search) == "do a barrel roll")
                {
                    $easterEgg = true;
                }

                $websites = $this->getDoctrine()->getRepository(Website::class)->createQueryBuilder('searchFilter')
                ->where('searchFilter.Name LIKE :search')
                ->setParameter('search', '%'.$search.'%')
                ->orderBy('searchFilter.date', 'DESC')
                ->getQuery()
                ->execute();

                $message = count($websites)." résultat pour \"".$search."\".";
                
                if (count($websites) > 1)
                {
                    $message = count($websites)." résultats pour \"".$search."\".";
                }
            }
            else
            {
                $websites = null;
                $error = "Une erreur s'est produite pendant la recherche.";
            }
        }
        else
        {
            $websites = $this->getDoctrine()->getRepository(Website::class)->findBy(
                array(),
                array('date' => 'DESC'),
            );

            if (empty($websites))
            {
                $message = "Aucun site.";
            }
            elseif (count($websites) == 1)
            {
                $message = count($websites)." site web.";
            }
            else
            {
                $message = count($websites)." sites web.";
            }
        }

        return $this->render('website/index.html.twig', [
            'websites' => $websites,
            'filtered' => $filtered,
            'message' => $message,
            'error' => $error,
            'easterEgg' => $easterEgg
        ]);
    }

    /**
     * @Route("/website/create", name="createWebsite")
     */
    public function createWebsite(Request $request, ValidatorInterface $validator): Response
    {
        if ($request->query->get('message') !== null)
        {
            $this->addFlash('notice', $request->query->get('message'));
        }

        if ($request->query->get('error') !== null)
        {
            $this->addFlash('error', $request->query->get('error'));
        }

        try
        {
            $website = new Website();

            $form = $this->createForm(WebsiteType::class, $website);
        
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $error = false;
                $errorMessage = "Erreur dans les champs suivants : ";
                $urlConstraint = new UrlConstraint();
                $choicesPHP = [
                    '7.4' => "7.4",
                    '7.3' => "7.3",
                    '7.2' => "7.2",
                    '7.1' => "7.1",
                    '7.0' => "7.0",
                ];

                if (null === $form->get('Name')->getData() || !is_string($form->get('Name')->getData()) || !preg_match("/^.{2,50}+$/", $form->get('Name')->getData()))
                {
                    $error = true;
                    $errorMessage = $errorMessage."Nom, ";
                }
                if (null === $form->get('Link')->getData() || !is_string($form->get('Link')->getData()) || count($validator->validate($form->get('Link')->getData(), $urlConstraint)) !== 0)
                {
                    $error = true;
                    $errorMessage = $errorMessage."Lien, ";
                }
                if (null === $form->get('Client')->getData() || !$form->get('Client')->getData() instanceof Client)
                {
                    $error = true;
                    $errorMessage = $errorMessage."Client, ";
                }
                if (null !== $form->get('PHP')->getData() && (!is_string($form->get('PHP')->getData()) || !in_array($form->get('PHP')->getData(), $choicesPHP)))
                {
                    $error = true;
                    $errorMessage = $errorMessage."Version PHP, ";
                }
                $errorMessage = substr($errorMessage, 0, -2);

                if ($error)
                {
                    return $this->redirectToRoute("createWebsite", [
                        'error' => $errorMessage,
                    ]);
                }

                $website = $form->getData();
                $website->setDate(new DateTime("NOW"));

                $manager = $this->getDoctrine()->getManager();
                $manager->persist($website);
                $manager->flush();

                return $this->redirectToRoute("createWebsite", [
                    'message' => 'Site '.$website->getName().' ajouté avec succès.',
                ]);
            }
        }
        catch (Exception $e)
        {
            return $this->redirectToRoute("createWebsite", [
                'error' => 'Une erreur s\'est produite.',
            ]);
        }

        return $this->render('website/create.html.twig', [
            'websiteForm' => $form->createView(),
        ]);
    }
}

templates/website/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Site{% endblock %}

{% block body %}
<style>
    
</style>

{{ form_start(websiteForm) }}
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for error in app.flashes('error') %}
            <div class="col-12 col-sm-10 col-md-8 my-2 alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
        {% for message in app.flashes('notice') %}
            <div class="col-12 col-sm-10 col-md-8 my-2 alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        <div class="col-12 text-center">
            <h1 class="my-3">Ajouter un Site</h1>
        </div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
            <div class="mb-2">
                {{ form_row(websiteForm.Name) }}
                {% if form_errors(websiteForm.Name) %}
                    <span class="labelError">Veuillez saisir un nom valide (2-50 caractères)</span>
                {% endif %}
            </div>
            <div class="mb-2">
                {{ form_row(websiteForm.Link) }}
                {% if form_errors(websiteForm.Link) %}
                    <span class="labelError">Veuillez saisir un lien valide</span>
                {% endif %}
            </div>
            <div class="mb-2">
                {{ form_row(websiteForm.Client) }}
                {% if form_errors(websiteForm.Client) %}
                    <span class="labelError">Veuillez sélectionner un client</span>
                {% endif %}
            </div>
            <div class="mb-2">
                {{ form_row(websiteForm.PHP) }}
            </div>
            <div class="mb-2 mt-2 text-center">
                {{ form_row(websiteForm.submit) }}
            </div>
            <div class="mb-2 mt-1 text-center">
                <span class="labelError">* Champs obligatoires</span>
            </div>
        </div>
    </div>
</div>
{{ form_end(websiteForm) }}
{% endblock %}

templates/website/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sites Web{% endblock %}

{% block body %}
{% if easterEgg %}
    <style>
        @keyframes roll {100%{transform:rotate(360deg)}}body{animation-name:roll;animation-duration:4s;animation-iteration-count:1}
    </style>
{% endif %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 my-2 text-center">
            {% if filtered == false %}
                <h1 class="my-3">Vos Sites Web</h1>
            {% else %}
                <h1 class="my-3">Résultat de Recherche</h1>
            {% endif %}
            {% if message is not null %}
                <label>{{ message }}</label>
            {% endif %}
            {% if error is not null %}
                <label class="labelError">{{ error }}</label>
            {% endif %}
        </div>
        {% if websites is not empty and websites is not null %}
            <div class="col-12 col-sm-10 col-md-8 col-lg-7 col-xl-6">
                <div class="accordion" id="websites">
                    {% for website in websites %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="accordion-label{{ website.id }}">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordion{{ website.id }}" aria-expanded="false" aria-controls="accordion{{ website.id }}">
                                    {{ website.name }}
                                </button>
                            </h2>
                            <div id="accordion{{ website.id }}" class="accordion-collapse collapse" aria-labelledby="accordion-label{{ website.id }}" data-bs-parent="#websites">
                                <div class="accordion-body">
                                    <h4 class="my-3"><strong>Site {{ website.name }}</strong></h4>
                                    <p>Lien : <a class="link" href="{{ website.link }}" target="_blank">{{ website.name }}</a></p>
                                    <p>Client : <a type="button" class="link" data-bs-toggle="modal" data-bs-target="#modal{{ website.id }}">{{ website.client.companyName }}</a></p>
                                    <p>Version PHP : 
                                        {% if website.php is not null %}
                                            <span class="soft">{{ website.php }}</span>
                                        {% else %}
                                            <span class="soft">Aucune</span>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>

                        {# Modal #}
                        <div class="modal fade" id="modal{{ website.id }}" tabindex="-1" aria-labelledby="modal-label{{ website.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="modal-label{{ website.id }}">Client {{ website.client.companyName }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Contact : <span class="soft">{{ website.client.contactName }}</span></p>
                                        <p>Email : 
                                            {% if website.client.contactEmail is not null %}
                                                <span class="soft">{{ website.client.contactEmail }}</span>
                                            {% else %}
                                                <span class="soft">Aucun</span>
                                            {% endif %}
                                        </p>
                                        <p>Téléphone : 
                                            {% if website.client.contactPhone is not null %}
                                                <span class="soft">{{ website.client.contactPhone }}</span>
                                            {% else %}
                                                <span class="soft">Aucun</span>
                                            {% endif %}
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Merci</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="col-12 text-center">
                <h2 class="bigSadFace">:(</h2>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}